[build]
  builder = "NIXPACKS"

[build.environment]
  PYTHON_VERSION = "3.12.7"

[deploy]
  startCommand = "cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
  numReplicas = 1
  maxRequestIdletime = "300s"
  maxRequestLifespan = "1000s"
